### ISSUE TITLE
StatusBarOverlaysWebView for PGB

### ISSUE THREAD

**Issue by red2678** [phonegap-build/StatusBarPlugin#23]
Hi Ryan,

Thanks for doing such a great job man with this plugin (and PGB). A lot of us use it, just saying. My question is when will this...

```
<preference name="StatusBarOverlaysWebView" value="true" />
```

...be supported by PhoneGap Build? 

Thanks again!

~Anthony

**Comment by orenagiv** [comment]
Hi anathony,

I'm not sure that should be part of the plugin, since you can now update the info.plist and control initial settings of the status bar. 

I will post here some examples later on, but in general - I would suggest that you configure the config.xml of PGB to start with the status bar "hidden" and then use the plugin JS to show it and set the overlay to TRUE or FALSE as you need.

**Comment by red2678** [comment]
Thanks @orenagiv ! An example would be awesome.

**Comment by orenagiv** [comment]
<gap:config-file platform="ios" parent="UIStatusBarHidden">
    <true/>
/gap:config-file

To set the StatusBar as hidden on iOS upon startup - use this in the PGB config.xml:

```
<gap:config-file platform="ios" parent="UIStatusBarHidden">
    <true/>
</gap:config-file>

<gap:config-file platform="ios" parent="UIViewControllerBasedStatusBarAppearance">
    < false/>
</gap:config-file>
```

**Comment by red2678** [comment]
Thanks man, got it! :+1:
